name: Checks
on:
  release:
    types: [published]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - name: Run Checks App Compliance analysis async
        uses: google-checks/checks-app-scan-github-action@latest
        with:
          account_id: "182222193"
          app_id: "1163119206"
          binary_path: "./example-app.apk"
          wait_for_report: true
        env:
          CHECKS_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_JSON }}